//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 19/09/2011 22:57:17
namespace Accessing_OData_Services.Mix11Reference
{
    
    /// <summary>
    /// There are no comments for eventsEntities in the schema.
    /// </summary>
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    public partial class eventsEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new eventsEntities object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public eventsEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("eventsModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("Accessing_OData_Services.Mix11Reference", typeName.Substring(11)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Accessing_OData_Services.Mix11Reference", global::System.StringComparison.Ordinal))
            {
                return string.Concat("eventsModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Session> Sessions
        {
            get
            {
                if ((this._Sessions == null))
                {
                    this._Sessions = base.CreateQuery<Session>("Sessions");
                }
                return this._Sessions;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Session> _Sessions;
        /// <summary>
        /// There are no comments for Speakers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Speaker> Speakers
        {
            get
            {
                if ((this._Speakers == null))
                {
                    this._Speakers = base.CreateQuery<Speaker>("Speakers");
                }
                return this._Speakers;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Speaker> _Speakers;
        /// <summary>
        /// There are no comments for Tags in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Tag> Tags
        {
            get
            {
                if ((this._Tags == null))
                {
                    this._Tags = base.CreateQuery<Tag>("Tags");
                }
                return this._Tags;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Tag> _Tags;
        /// <summary>
        /// There are no comments for Files in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<File> Files
        {
            get
            {
                if ((this._Files == null))
                {
                    this._Files = base.CreateQuery<File>("Files");
                }
                return this._Files;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<File> _Files;
        /// <summary>
        /// There are no comments for Sessions in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSessions(Session session)
        {
            base.AddObject("Sessions", session);
        }
        /// <summary>
        /// There are no comments for Speakers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSpeakers(Speaker speaker)
        {
            base.AddObject("Speakers", speaker);
        }
        /// <summary>
        /// There are no comments for Tags in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTags(Tag tag)
        {
            base.AddObject("Tags", tag);
        }
        /// <summary>
        /// There are no comments for Files in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToFiles(File file)
        {
            base.AddObject("Files", file);
        }
    }
    /// <summary>
    /// There are no comments for eventsModel.Session in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SessionID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Sessions")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Data.Services.Common.EntityPropertyMappingAttribute("Abstract", System.Data.Services.Common.SyndicationItemProperty.Summary, System.Data.Services.Common.SyndicationTextContentKind.Plaintext, false)]
    [global::System.Data.Services.Common.EntityPropertyMappingAttribute("Title", System.Data.Services.Common.SyndicationItemProperty.Title, System.Data.Services.Common.SyndicationTextContentKind.Plaintext, false)]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("SessionID")]
    public partial class Session : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Session object.
        /// </summary>
        /// <param name="sessionID">Initial value of SessionID.</param>
        /// <param name="eventCode">Initial value of EventCode.</param>
        /// <param name="sessionCode">Initial value of SessionCode.</param>
        /// <param name="sessionTypeCode">Initial value of SessionTypeCode.</param>
        /// <param name="publishFlag">Initial value of PublishFlag.</param>
        /// <param name="title">Initial value of Title.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Session CreateSession(int sessionID, string eventCode, string sessionCode, string sessionTypeCode, bool publishFlag, string title)
        {
            Session session = new Session();
            session.SessionID = sessionID;
            session.EventCode = eventCode;
            session.SessionCode = sessionCode;
            session.SessionTypeCode = sessionTypeCode;
            session.PublishFlag = publishFlag;
            session.Title = title;
            return session;
        }
        /// <summary>
        /// There are no comments for Property SessionID in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SessionID
        {
            get
            {
                return this._SessionID;
            }
            set
            {
                this.OnSessionIDChanging(value);
                this._SessionID = value;
                this.OnSessionIDChanged();
                this.OnPropertyChanged("SessionID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SessionID;
        partial void OnSessionIDChanging(int value);
        partial void OnSessionIDChanged();
        /// <summary>
        /// There are no comments for Property EventCode in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string EventCode
        {
            get
            {
                return this._EventCode;
            }
            set
            {
                this.OnEventCodeChanging(value);
                this._EventCode = value;
                this.OnEventCodeChanged();
                this.OnPropertyChanged("EventCode");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _EventCode;
        partial void OnEventCodeChanging(string value);
        partial void OnEventCodeChanged();
        /// <summary>
        /// There are no comments for Property SessionCode in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SessionCode
        {
            get
            {
                return this._SessionCode;
            }
            set
            {
                this.OnSessionCodeChanging(value);
                this._SessionCode = value;
                this.OnSessionCodeChanged();
                this.OnPropertyChanged("SessionCode");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SessionCode;
        partial void OnSessionCodeChanging(string value);
        partial void OnSessionCodeChanged();
        /// <summary>
        /// There are no comments for Property SessionTypeCode in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SessionTypeCode
        {
            get
            {
                return this._SessionTypeCode;
            }
            set
            {
                this.OnSessionTypeCodeChanging(value);
                this._SessionTypeCode = value;
                this.OnSessionTypeCodeChanged();
                this.OnPropertyChanged("SessionTypeCode");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SessionTypeCode;
        partial void OnSessionTypeCodeChanging(string value);
        partial void OnSessionTypeCodeChanged();
        /// <summary>
        /// There are no comments for Property Level in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<short> Level
        {
            get
            {
                return this._Level;
            }
            set
            {
                this.OnLevelChanging(value);
                this._Level = value;
                this.OnLevelChanged();
                this.OnPropertyChanged("Level");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<short> _Level;
        partial void OnLevelChanging(global::System.Nullable<short> value);
        partial void OnLevelChanged();
        /// <summary>
        /// There are no comments for Property Abstract in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Abstract
        {
            get
            {
                return this._Abstract;
            }
            set
            {
                this.OnAbstractChanging(value);
                this._Abstract = value;
                this.OnAbstractChanged();
                this.OnPropertyChanged("Abstract");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Abstract;
        partial void OnAbstractChanging(string value);
        partial void OnAbstractChanged();
        /// <summary>
        /// There are no comments for Property PublishFlag in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool PublishFlag
        {
            get
            {
                return this._PublishFlag;
            }
            set
            {
                this.OnPublishFlagChanging(value);
                this._PublishFlag = value;
                this.OnPublishFlagChanged();
                this.OnPropertyChanged("PublishFlag");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _PublishFlag;
        partial void OnPublishFlagChanging(bool value);
        partial void OnPublishFlagChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Room in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Room
        {
            get
            {
                return this._Room;
            }
            set
            {
                this.OnRoomChanging(value);
                this._Room = value;
                this.OnRoomChanged();
                this.OnPropertyChanged("Room");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Room;
        partial void OnRoomChanging(string value);
        partial void OnRoomChanged();
        /// <summary>
        /// There are no comments for Property StartTime in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> StartTime
        {
            get
            {
                return this._StartTime;
            }
            set
            {
                this.OnStartTimeChanging(value);
                this._StartTime = value;
                this.OnStartTimeChanged();
                this.OnPropertyChanged("StartTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _StartTime;
        partial void OnStartTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnStartTimeChanged();
        /// <summary>
        /// There are no comments for Property Duration in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> Duration
        {
            get
            {
                return this._Duration;
            }
            set
            {
                this.OnDurationChanging(value);
                this._Duration = value;
                this.OnDurationChanged();
                this.OnPropertyChanged("Duration");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _Duration;
        partial void OnDurationChanging(global::System.Nullable<int> value);
        partial void OnDurationChanged();
        /// <summary>
        /// There are no comments for Speakers in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Speaker> Speakers
        {
            get
            {
                return this._Speakers;
            }
            set
            {
                this._Speakers = value;
                this.OnPropertyChanged("Speakers");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Speaker> _Speakers = new global::System.Data.Services.Client.DataServiceCollection<Speaker>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Tags in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Tag> Tags
        {
            get
            {
                return this._Tags;
            }
            set
            {
                this._Tags = value;
                this.OnPropertyChanged("Tags");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Tag> _Tags = new global::System.Data.Services.Client.DataServiceCollection<Tag>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Files in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<File> Files
        {
            get
            {
                return this._Files;
            }
            set
            {
                this._Files = value;
                this.OnPropertyChanged("Files");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<File> _Files = new global::System.Data.Services.Client.DataServiceCollection<File>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for eventsModel.Speaker in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SpeakerID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Speakers")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Data.Services.Common.EntityPropertyMappingAttribute("FirstName", System.Data.Services.Common.SyndicationItemProperty.Title, System.Data.Services.Common.SyndicationTextContentKind.Plaintext, false)]
    [global::System.Data.Services.Common.EntityPropertyMappingAttribute("Bio", System.Data.Services.Common.SyndicationItemProperty.Summary, System.Data.Services.Common.SyndicationTextContentKind.Plaintext, false)]
    [global::System.Data.Services.Common.HasStreamAttribute()]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("SpeakerID")]
    public partial class Speaker : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Speaker object.
        /// </summary>
        /// <param name="speakerID">Initial value of SpeakerID.</param>
        /// <param name="firstName">Initial value of FirstName.</param>
        /// <param name="lastName">Initial value of LastName.</param>
        /// <param name="externalSpeaker">Initial value of ExternalSpeaker.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Speaker CreateSpeaker(int speakerID, string firstName, string lastName, bool externalSpeaker)
        {
            Speaker speaker = new Speaker();
            speaker.SpeakerID = speakerID;
            speaker.FirstName = firstName;
            speaker.LastName = lastName;
            speaker.ExternalSpeaker = externalSpeaker;
            return speaker;
        }
        /// <summary>
        /// There are no comments for Property SpeakerID in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SpeakerID
        {
            get
            {
                return this._SpeakerID;
            }
            set
            {
                this.OnSpeakerIDChanging(value);
                this._SpeakerID = value;
                this.OnSpeakerIDChanged();
                this.OnPropertyChanged("SpeakerID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SpeakerID;
        partial void OnSpeakerIDChanging(int value);
        partial void OnSpeakerIDChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property Bio in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Bio
        {
            get
            {
                return this._Bio;
            }
            set
            {
                this.OnBioChanging(value);
                this._Bio = value;
                this.OnBioChanged();
                this.OnPropertyChanged("Bio");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Bio;
        partial void OnBioChanging(string value);
        partial void OnBioChanged();
        /// <summary>
        /// There are no comments for Property PhotoUri in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PhotoUri
        {
            get
            {
                return this._PhotoUri;
            }
            set
            {
                this.OnPhotoUriChanging(value);
                this._PhotoUri = value;
                this.OnPhotoUriChanged();
                this.OnPropertyChanged("PhotoUri");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PhotoUri;
        partial void OnPhotoUriChanging(string value);
        partial void OnPhotoUriChanged();
        /// <summary>
        /// There are no comments for Property Notes in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Notes
        {
            get
            {
                return this._Notes;
            }
            set
            {
                this.OnNotesChanging(value);
                this._Notes = value;
                this.OnNotesChanged();
                this.OnPropertyChanged("Notes");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Notes;
        partial void OnNotesChanging(string value);
        partial void OnNotesChanged();
        /// <summary>
        /// There are no comments for Property ExternalSpeaker in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool ExternalSpeaker
        {
            get
            {
                return this._ExternalSpeaker;
            }
            set
            {
                this.OnExternalSpeakerChanging(value);
                this._ExternalSpeaker = value;
                this.OnExternalSpeakerChanged();
                this.OnPropertyChanged("ExternalSpeaker");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _ExternalSpeaker;
        partial void OnExternalSpeakerChanging(bool value);
        partial void OnExternalSpeakerChanged();
        /// <summary>
        /// There are no comments for Sessions in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Session> Sessions
        {
            get
            {
                return this._Sessions;
            }
            set
            {
                this._Sessions = value;
                this.OnPropertyChanged("Sessions");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Session> _Sessions = new global::System.Data.Services.Client.DataServiceCollection<Session>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for eventsModel.Tag in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TagID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Tags")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("TagID")]
    public partial class Tag : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Tag object.
        /// </summary>
        /// <param name="tagID">Initial value of TagID.</param>
        /// <param name="tagValue">Initial value of TagValue.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Tag CreateTag(int tagID, string tagValue)
        {
            Tag tag = new Tag();
            tag.TagID = tagID;
            tag.TagValue = tagValue;
            return tag;
        }
        /// <summary>
        /// There are no comments for Property TagID in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int TagID
        {
            get
            {
                return this._TagID;
            }
            set
            {
                this.OnTagIDChanging(value);
                this._TagID = value;
                this.OnTagIDChanged();
                this.OnPropertyChanged("TagID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _TagID;
        partial void OnTagIDChanging(int value);
        partial void OnTagIDChanged();
        /// <summary>
        /// There are no comments for Property TagValue in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TagValue
        {
            get
            {
                return this._TagValue;
            }
            set
            {
                this.OnTagValueChanging(value);
                this._TagValue = value;
                this.OnTagValueChanged();
                this.OnPropertyChanged("TagValue");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TagValue;
        partial void OnTagValueChanging(string value);
        partial void OnTagValueChanged();
        /// <summary>
        /// There are no comments for Sessions in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Session> Sessions
        {
            get
            {
                return this._Sessions;
            }
            set
            {
                this._Sessions = value;
                this.OnPropertyChanged("Sessions");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Session> _Sessions = new global::System.Data.Services.Client.DataServiceCollection<Session>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for eventsModel.File in the schema.
    /// </summary>
    /// <KeyProperties>
    /// FileID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Files")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Data.Services.Common.HasStreamAttribute()]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("FileID")]
    public partial class File : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new File object.
        /// </summary>
        /// <param name="fileID">Initial value of FileID.</param>
        /// <param name="mimeType">Initial value of MimeType.</param>
        /// <param name="fileUri">Initial value of FileUri.</param>
        /// <param name="sessionID">Initial value of SessionID.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static File CreateFile(int fileID, string mimeType, string fileUri, int sessionID)
        {
            File file = new File();
            file.FileID = fileID;
            file.MimeType = mimeType;
            file.FileUri = fileUri;
            file.SessionID = sessionID;
            return file;
        }
        /// <summary>
        /// There are no comments for Property FileID in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int FileID
        {
            get
            {
                return this._FileID;
            }
            set
            {
                this.OnFileIDChanging(value);
                this._FileID = value;
                this.OnFileIDChanged();
                this.OnPropertyChanged("FileID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _FileID;
        partial void OnFileIDChanging(int value);
        partial void OnFileIDChanged();
        /// <summary>
        /// There are no comments for Property MimeType in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MimeType
        {
            get
            {
                return this._MimeType;
            }
            set
            {
                this.OnMimeTypeChanging(value);
                this._MimeType = value;
                this.OnMimeTypeChanged();
                this.OnPropertyChanged("MimeType");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MimeType;
        partial void OnMimeTypeChanging(string value);
        partial void OnMimeTypeChanged();
        /// <summary>
        /// There are no comments for Property FileUri in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FileUri
        {
            get
            {
                return this._FileUri;
            }
            set
            {
                this.OnFileUriChanging(value);
                this._FileUri = value;
                this.OnFileUriChanged();
                this.OnPropertyChanged("FileUri");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FileUri;
        partial void OnFileUriChanging(string value);
        partial void OnFileUriChanged();
        /// <summary>
        /// There are no comments for Property SessionID in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SessionID
        {
            get
            {
                return this._SessionID;
            }
            set
            {
                this.OnSessionIDChanging(value);
                this._SessionID = value;
                this.OnSessionIDChanged();
                this.OnPropertyChanged("SessionID");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SessionID;
        partial void OnSessionIDChanging(int value);
        partial void OnSessionIDChanged();
        /// <summary>
        /// There are no comments for Session in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Session Session
        {
            get
            {
                return this._Session;
            }
            set
            {
                this._Session = value;
                this.OnPropertyChanged("Session");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Session _Session;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
